In [1]:
import wikipedia
import wikipediaapi

In [2]:
import pandas as pd
df = pd.read_excel(r"<data_path>\user_names.xlsx")
print(df.shape)
print(df.head())

(3700, 1)
         Usernames
0  $1LENCE D00600D
1     (CA)Giacobbe
2        117Avenue
3        12george1
4              172

In [3]:
userid = []
editcount = []
gender = []
blockinfo = []
emailable = []

In [4]:
for i in range(1,76):
    a = df["Usernames"][(i-1)*49:i*49]
    U = ""
    for n in range(len(a)):
        b = a.values[n]
        U = U + str(b) + "|"
    
    import requests
    S = requests.Session()

    URL = "https://en.wikipedia.org/w/api.php"

    PARAMS = {
        "action": "query",
        "format": "json",
        "list": "users",
        "ususers": str(U),
        "usprop": "blockinfo|editcount|emailable|gender"
    }

    R = S.get(url=URL, params=PARAMS)
    DATA = R.json()
    DATA["query"]["users"].pop(0)

    USERS = DATA["query"]["users"]
    
    for u in USERS:
        if 'userid' in u:
            userid.append(u["userid"])
        else:
            userid.append("unknown")
        if 'editcount' in u:
            editcount.append(u["editcount"])
        else:
            editcount.append("unknown")
        if 'gender' in u:
            gender.append(u["gender"])
        else:
            gender.append("unknown")
        if 'emailable' in u:
            emailable.append(1)
        else:
            emailable.append(0)
        if 'blockid' in u:
            blockinfo.append(1)
        else:
            blockinfo.append(0)
    
    for j in range((i-1)*49,i*49):
        df.loc[j, "User ID"] = int(userid[j])
        df.loc[j,'Edit  Count'] = int(editcount[j])
        df.loc[j,'Gender'] = gender[j]
        df.loc[j,'Blockinfo'] = int(blockinfo[j])
        df.loc[j,'Emailable'] = int(emailable[j])

In [5]:
for i in range(1,2):
    a = df["Usernames"][3675:3700]
    U = ""
    for n in range(len(a)):
        b = a.values[n]
        U = U + str(b) + "|"
    
    import requests
    S = requests.Session()

    URL = "https://en.wikipedia.org/w/api.php"

    PARAMS = {
        "action": "query",
        "format": "json",
        "list": "users",
        "ususers": str(U),
        "usprop": "blockinfo|editcount|emailable|gender"
    }

    R = S.get(url=URL, params=PARAMS)
    DATA = R.json()
    DATA["query"]["users"].pop(0)

    USERS = DATA["query"]["users"]
    
    for u in USERS:
        if 'userid' in u:
            userid.append(u["userid"])
        else:
            userid.append("unknown")
        if 'editcount' in u:
            editcount.append(u["editcount"])
        else:
            editcount.append("unknown")
        if 'gender' in u:
            gender.append(u["gender"])
        else:
            gender.append("unknown")
        if 'emailable' in u:
            emailable.append(1)
        else:
            emailable.append(0)
        if 'blockid' in u:
            blockinfo.append(1)
        else:
            blockinfo.append(0)
    
    for j in range(3675,3700):
        df.loc[j, "User ID"] = int(userid[j])
        df.loc[j,'Edit  Count'] = int(editcount[j])
        df.loc[j,'Gender'] = gender[j]
        df.loc[j,'Blockinfo'] = int(blockinfo[j])
        df.loc[j,'Emailable'] = int(emailable[j])

In [ ]:
for i in range(1,3700):
    a = df["Usernames"][i]
    try:
        df.loc[i, "About"] = wikipedia.summary("User:"+str(a))
    except:
        df.loc[i, "About"] = "unknown"

In [10]:
df

,Usernames,User ID,Edit Count,Gender,Blockinfo,Emailable,About
0,$1LENCE D00600D,12827524,18642.0,unknown,1.0,0.0,NaN
1,(CA)Giacobbe,15033274.0,19066.0,male,0.0,0.0,"Hello everybody, I'm (CA)Giacobbe, but prefer ..."
2,117Avenue,9535527.0,64442.0,male,0.0,1.0,The link I use when I want a casual drive to a...
3,12george1,7462941.0,29152.0,male,0.0,1.0,"Hello, my name is George. I became a Wikipedia..."
4,172,6523.0,24875.0,unknown,1.0,1.0,CheckUser evidence has shown that 172 is the s...
...,...,...,...,...,...,...,...
3695,Â²Â¹Â²,5756587,64361,male,0.0,1.0,This is my user page.À á â a̋ ȁ a̖ a̗ a̭ Accen...
3696,ÂºÂ¡Âº,unknown,unknown,unknown,0.0,0.0,<?php\n/* Gaeilge - Irish */\n/*\nSeo Ã© an da...
3697,Î¤Î±ÏƒÎ¿Ï…Î»Î±,unknown,unknown,unknown,0.0,0.0,Þ«î£... â¡ î°FŠ ð†®ò™: àƒèÀì¡\nMõ£F‚è «õÁ...
3698,ã¨ã‚ã‚‹ç™½ã„çŒ«,unknown,unknown,unknown,0.0,0.0,en:User:Mathglot (contributions) (talk)\n ...
3699,2005,96240,25169,unknown,0.0,0.0,2009 (MMIX) was a common year starting on Thur...

In [40]:
df.to_excel(r'<data_path>\final.xlsx', index = False, engine='xlsxwriter')